services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "9000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - php
      - db
    networks:
      - app-network

  php:
    build:
      context: ./docker/php
    container_name: php
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3399:3306" 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: publipista
      MYSQL_USER: lamp
      MYSQL_PASSWORD: lamp
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
